smurf: pol2map: Remove non-ASCII characters
The non-ASCII micro characters that were in there cause python to fall
over on some systems:

File "/net/rogue1/work/jkaroly/star_CentOS6/star-nightly/bin/smurf/pol2map.py", line 525
SyntaxError: Non-ASCII character '\xce' in file /net/rogue1/work/jkaroly/star_CentOS6/star-nightly/bin/smurf/pol2map.py on line 526,
but no encoding declared;
see http://python.org/dev/peps/pep-0263/ for details

(cherry picked from commit f3fa33e84c808b35845331f8538a7c87941a5e16)